### ISSUE TITLE
Improve Canary functionality (new Neptune things + gplugins)

### ISSUE THREAD

**Issue by jamierocks** [minecraft-dev/MinecraftDev#129]
## Tasks

- [x] Neptune Changes
    - [x] Support Neptune.inf
- [ ] Generate plugin code using gplugins
    - [ ] Do not generate Neptune.inf
    - [ ] Allow `HookHandler`s in classes annotated with `@Plugin`
